
###
GET http://localhost:3001/todos

###
POST http://localhost:3001/todo/new
Content-Type: application/json

{
    "text":"study"
}
###
DELETE  http://localhost:3001/todo/delete/646fb407ff63405c09de5f72

###
PUT     http://localhost:3001/todo/complete/646d3426b9b4a577e186a4d5


