
###
GET http://localhost:5000/todos

###
POST http://localhost:5000/todo/new
Content-Type: application/json

{
    "text":"sport"
}
###
DELETE  http://localhost:5000/todo/delete/646d0c7e5f3941fe8be83150

###
PUT     http://localhost:5000/todo/complete/646d3426b9b4a577e186a4d5


